[build]
builder = "nixpacks"
buildCommand = "poetry install && cd ./human_preference_collector/frontend && npm install && npm run build"

[deploy]
startCommand = "cd ./human_preference_collector && poetry run gunicorn backend.server:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"