[build]
builder = "nixpacks"
buildCommand = """
  rm -rf /root/.cache/pip
  pip install --no-cache-dir --no-deps -r ./human_preference_collector/requirements.txt
  cd ./human_preference_collector/frontend && npm install && npm run build
"""
[deploy]
startCommand = "cd ./human_preference_collector && poetry run gunicorn backend.server:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"